# Probability
## Introduction to Probabilities
In 1814, Pierre-Simon Laplace wrote:  
> Probability theory is nothing but common sense reduced to calculation. 
... [Probability] is thus simply a fraction whose numerator is the 
number of favorable cases and whose denominator is the number of all 
the cases possible ... when nothing leads us to expect that any one of 
these cases should occur more than any other.
Laplace nailed it. To untangle a probability problem, all you have to do 
is define exactly what the cases are, and careful count the favorable 
and total cases. Let's be clear on our vocabulary words:
- **Trial**
A single occurrence with an outcome that is uncertain until we observe it.  
*For example, rolling a single die.*
- **Outcome**
A possible result of a trial; one particular state of the world. What 
Laplace calls a **case.** *For example:* `4`.
- **Sample Space**
The set of all possible outcomes for the trial.   
*For example,* `{1, 2, 3, 4, 5, 6}`.
- **Event**
A subset of the sample space, a set of outcomes that together have some 
property we are interested in.  
*For example, the event "even die roll" is the set of outcomes* 
`{2, 4, 6}`.
- **Probability**
As Laplace said, the probability of an event with respect to a sample 
space is the "number of favorable cases" (outcomes from the sample space 
that are in the event) divided by the "number of all the cases" in the 
sample space (assuming "nothing leads us to expect that any one of these 
cases should occur more than any other"). Since this is a proper 
fraction, probability will always be a number between 0 (representing an 
impossible event) and 1 (representing a certain event).  
*For example, the probability of an even die roll is 3/6 = 1/2.*


In [199]:
import random #Generador de numeros aleatorios
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#1. Generacion de lanzamiento de una moneda
toss = random.randint(0,1)

if toss == 1:
    print("sello")
else:
    print("cara")


cara


In [166]:
#Generacion de lanzamiento de monedas, con una estructura de contro (for) las secuencias de control son for if while
toss_results = []
for i in range(10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)

[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]


In [167]:
#Generacion de lanzamiento de monedas controlado para ser replicable.
random.seed(2024)
toss_results = []
for i in range(10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)

[1, 0, 1, 0, 1, 1, 0, 1, 1, 1]


In [168]:
#Calcular la probabilidad de que salga cara con 10 lanzamientos de moneda
toss_results = []
for i in range(100):
    result = random.randint(0,1)
    toss_results.append(result)
#print(toss_results)
sum(toss_results)/len(toss_results)

0.48

In [169]:
from fractions import Fraction

In [170]:
Fraction(1,3) #Representacion de una fraccion en Python

Fraction(1, 3)

In [171]:
#2 Calcular la probabilidad de sacar par en un lanzamineto de dados
even = {2,4,6}
points = {1,2,3,4,5,6} #Asumimos que el dado esta balanceado.
set.intersection(even,points)


{2, 4, 6}

In [172]:
def Pr(event,space):
    return Fraction(len(set.intersection(event,space)),len(space))


In [173]:
Pr(even,points)

Fraction(1, 2)

In [174]:
#Calcular la probabilidad de obterner 5 o 6 en un lanzamiento de datos
success = {5,6}
points = {1,2,3,4,5,6}
Pr(success,points)

Fraction(1, 3)

This refers to a discrete sample space, so the probability is related to a discrete event

In [175]:
# box1 = [1,0,0,0] la probabilidad de exito es de 1/4 = 0.25
# box2 = [1,1,0,0,0] la probabilidad de exito es de 2/5 = 0.4

box1 = np.array([1,0,0,0])
np.random.choice(box1,1) #Valor random

array([0])

In [176]:
trial = np.random.choice(box1,1000000) #Valor random 10000 veces
trial.mean() #Promedio de veces / probabilidad, mean funciona porque solo hay 2 posibles valores 0 o 1 

np.float64(0.249693)

In [177]:
box2 = np.array([1,0,1,0,0])
trial = np.random.choice(box2,1000000)
trial.mean()

np.float64(0.400591)

In [178]:
#cuando son mas de dos resultados se usa 

success = np.isin(trial,[1])
probability = len (trial[success])/len(trial)
probability

0.400591

In [179]:
yankenpo = np.array([1,2,3])
trial = np.random.choice(yankenpo,10)
success = np.isin(trial,[2]) #isin nos retorna un vector de booleanos
probability = len (trial[success])/len(trial)
probability

0.4

In [180]:
yankenpo
trial
success

array([False, False,  True,  True,  True,  True, False, False, False,
       False])

In [181]:
trial

array([3, 3, 2, 2, 2, 2, 3, 1, 3, 3])

In [182]:
trial[success]

array([2, 2, 2, 2])

In [183]:
results = np.array ([14,22,21,15,18,23,19])
success = np.isin(results, [21])
results[success]

array([21])

In [184]:
#Probabilidad condicional
#Probabilidad de sacar un As en una segunda extraccion si en una primera extraccion sauqe un As
# Una baraja de 52 naipes tiene 4 Ases

In [208]:
def same_birthday(n):
    days = np.arange(1,366)
    bday = np.random.choice(days,n)
    return np.any(np.bincount(bday)>1)




np.False_

In [233]:
same_birthday(10)
counter = 0 
for i in range(10000):
    if same_birthday(50):
        counter+=1
counter/10000

0.9686